version: "3.7"

services:

  rust:
    container_name: rust
    build:
      context: ./graphql
      target: developer
    volumes:
      - ./graphql:/app
      - ./graphql/cache/cargo:/usr/local/cargo/registry
    ports:
      - 8080:8080
    command: bash ./sh/setup.sh
    environment:
      TZ: Asia/Tokyo

  node:
    container_name: node
    build:
      context: ./frontend
      target: developer
    volumes:
      - ./frontend:/app
    ports:
      - 3000:3000
      - 6006:6006
    command: bash ./sh/setup.sh
    environment:
      TZ: Asia/Tokyo

  redis:
    container_name: redis
    build:
      context: ./session
    volumes:
      - ./session/data:/data
    ports:
      - 6379:6379
    command: bash /tmp/setup.sh
    environment:
      TZ: Asia/Tokyo

  mysql:
    container_name: mysql
    build:
      context: ./database
    volumes:
      - ./database/data:/var/lib/mysql
      - ./database/logs:/var/log/mysql
    ports:
      - 3306:3306
    command: bash /tmp/setup.sh
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: links_dev
      MYSQL_USER: links_app
      MYSQL_PASSWORD: secret
      UID: ${USER_ID:-1000}
      GID: ${GROUP_ID:-1000}
      TZ: Asia/Tokyo
