import { NextPage } from 'next'
import Head from 'next/head'
import React from 'react'

const Error: NextPage = () => {
  return (
    <div>
      <Head>
        <title>error</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      エラーが発生した
    </div>
  )
}

export default Error
