import { addApolloState, initializeApollo } from 'graphql/apollo'
import { IsAuthenticatedDocument } from 'graphql/generated'
import { GetServerSideProps, NextPage } from 'next'
import Head from 'next/head'
import React from 'react'

const Login: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Login</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      ログインページです
    </div>
  )
}

export const getServerSideProps: GetServerSideProps = async (ctx) => {
  const apolloClient = initializeApollo()
  const cookie = ctx.req.headers.cookie
  const context = { headers: { cookie } }

  const {
    data: { isAuthenticated }
  } = await apolloClient.query({ query: IsAuthenticatedDocument, context })

  if (isAuthenticated) {
    return {
      redirect: {
        permanent: false,
        destination: '/'
      }
    }
  }

  return addApolloState(apolloClient, {
    props: {}
  })
}

export default Login
